/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestMorgan from "nest-morgan";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OrderService } from "../order.service";
import { OrderCreateInput } from "./OrderCreateInput";
import { OrderWhereUniqueInput } from "./OrderWhereUniqueInput";
import { OrderFindManyArgs } from "./OrderFindManyArgs";
import { OrderUpdateInput } from "./OrderUpdateInput";
import { Order } from "./Order";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { RestPermissionsInterceptor } from "src/interceptors/restPermissions.interceptor";
import { ProductCreateNestedManyWithoutOrdersInput } from "./ProductCreateNestedManyWithoutOrdersInput";
import { ProductUpdateManyWithoutOrdersInput } from "./ProductUpdateManyWithoutOrdersInput";

@swagger.ApiBearerAuth()
@common.UseGuards(
  defaultAuthGuard.DefaultAuthGuard,
  nestAccessControl.ACGuard
)
@common.UseInterceptors(RestPermissionsInterceptor)
export class OrderControllerBase {
  constructor(
    protected readonly service: OrderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: Order })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: OrderCreateInput,
  ): Promise<Order> {
    console.log('order');
    return await this.service.create({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        quantity: true,
        discount: true,
        totalPrice: true,

        customer: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: [Order] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(OrderFindManyArgs)
  async findMany(
    @common.Req() request: Request,
  ): Promise<Order[]> {
    const args = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        quantity: true,
        discount: true,
        totalPrice: true,

        customer: {
          select: {
            id: true,
          },
        },
      },
    });
    return results;
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: Order })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: OrderWhereUniqueInput,
  ): Promise<Order | null> {

    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        quantity: true,
        discount: true,
        totalPrice: true,

        customer: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Order })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body()
    data: OrderUpdateInput,
  ): Promise<Order | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          quantity: true,
          discount: true,
          totalPrice: true,

          customer: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Order })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: OrderWhereUniqueInput
  ): Promise<Order | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          quantity: true,
          discount: true,
          totalPrice: true,

          customer: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.Get("/:id/product")
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "read",
    possession: "any",
  })
  @ApiNestedQuery(ProductFindManyArgs)
  async findManyProduct(
    @common.Req() request: Request,
    @common.Param() params: OrderWhereUniqueInput,
  ): Promise<Product[]> {
    const query = plainToClass(ProductFindManyArgs, request.query);
    const results = await this.service.findProduct(params.id, {
      ...query,
      select: {
        createdAt: true,
        name: true,
        itemPrice: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.Post("/:id/product")
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "update",
    possession: "any",
  })
  async createProduct(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body() body: ProductCreateNestedManyWithoutOrdersInput,
    // @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      product: body,
    };
    // const permission = this.rolesBuilder.permission({
    //   role: userRoles,
    //   action: "update",
    //   possession: "any",
    //   resource: "Order",
    // });
    // const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    // if (invalidAttributes.length) {
    //   const roles = userRoles
    //     .map((role: string) => JSON.stringify(role))
    //     .join(",");
    //   throw new common.ForbiddenException(
    //     `Updating the relationship: ${
    //       invalidAttributes[0]
    //     } of ${"Order"} is forbidden for roles: ${roles}`
    //   );
    // }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.Patch("/:id/product")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async updateProduct(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body() body: ProductUpdateManyWithoutOrdersInput,
    // @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      product: body,
    };
    // const permission = this.rolesBuilder.permission({
    //   role: userRoles,
    //   action: "update",
    //   possession: "any",
    //   resource: "Product",
    // });
    
    // const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    // if (invalidAttributes.length) {      
    //   const roles = userRoles
    //     .map((role: string) => JSON.stringify(role))
    //     .join(",");
    //   throw new common.ForbiddenException(
    //     `Updating the relationship: ${
    //       invalidAttributes[0]
    //     } of ${"Order"} is forbidden for roles: ${roles}`
    //   );
    // }
    this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.Delete("/:id/product")
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "update",
    possession: "any",
  })
  async deleteProduct(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[],
    // @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      product: {
        disconnect: body,
      },
    };
    // const permission = this.rolesBuilder.permission({
    //   role: userRoles,
    //   action: "update",
    //   possession: "any",
    //   resource: "Order",
    // });
    // const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    // if (invalidAttributes.length) {
    //   const roles = userRoles
    //     .map((role: string) => JSON.stringify(role))
    //     .join(",");
    //   throw new common.ForbiddenException(
    //     `Updating the relationship: ${
    //       invalidAttributes[0]
    //     } of ${"Order"} is forbidden for roles: ${roles}`
    //   );
    // }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
